### PR TITLE
Sprint

### PR DESCRIPTION
**Pull request by mancap**
This change is [Reviewable](https://reviewable.io/reviews/mancap/branching/5)

### CODE REVIEW

**Review by mancap — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mancap/branching/5)* status: 0 of 1 files reviewed, 2 unresolved discussions

___
*[CHANGELOG.md, line 3 at r1](https://reviewable.io/reviews/mancap/branching/5#-LQfGd__5gnSrHieoMqj:-LQfGd__5gnSrHieoMqk:b-bdckdj) ([raw file](https://github.com/mancap/branching/blob/2e111686e11bd9645c3369a21d84591f799b9056/CHANGELOG.md#L3)):*
> ```Markdown
> ## v1.2.0 (TDB)
> 
> Changes:
> ```

Why changes?
___
*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/mancap/branching/5#-LQfG_dIAgOnctZXjUMU:-LQfG_dJCDflKwjKeV5p:b-5nd9zh) ([raw file](https://github.com/mancap/branching/blob/2e111686e11bd9645c3369a21d84591f799b9056/CHANGELOG.md#L7)):*
> ```Markdown
> Features:
> 
> Bugfixes:
> ```

Why bugfixes?

**Review by mancap — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mancap/branching/5)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @mancap)

___
*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/mancap/branching/5#-LQfG_dIAgOnctZXjUMU:-LQfHYf_7FlCdU-JnV3E:bebrt1w) ([raw file](https://github.com/mancap/branching/blob/2e111686e11bd9645c3369a21d84591f799b9056/CHANGELOG.md#L7)):*
<details><summary><i>Previously, mancap (Manca Pezzot) wrote…</i></summary><blockquote>

Why bugfixes?
</blockquote></details>

Will do

**Review by gbaasch — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/mancap/branching/5)* status: all files reviewed, 2 unresolved discussions (waiting on @mancap)

___
*[CHANGELOG.md, line 3 at r1](https://reviewable.io/reviews/mancap/branching/5#-LQfGd__5gnSrHieoMqj:-LQfW7Z7-ZRcgLLGUD4Y:bsyyrue) ([raw file](https://github.com/mancap/branching/blob/2e111686e11bd9645c3369a21d84591f799b9056/CHANGELOG.md#L3)):*
<details><summary><i>Previously, mancap (Manca Pezzot) wrote…</i></summary><blockquote>

Why changes?
</blockquote></details>

There just where

**Review by gbaasch — COMMENTED** [review]
Hekl

> *[Reviewable](https://reviewable.io/reviews/mancap/branching/5#-:-LQfWYNk3GUfuPajMyZc:bb6wzib)* status: all files reviewed, 2 unresolved discussions (waiting on @mancap)

___
*[CHANGELOG.md, line 7 at r1](https://reviewable.io/reviews/mancap/branching/5#-LQfG_dIAgOnctZXjUMU:-LQfW_3x8PJYZU8NT2Ev:b-7pk9ar) ([raw file](https://github.com/mancap/branching/blob/2e111686e11bd9645c3369a21d84591f799b9056/CHANGELOG.md#L7)):*
<details><summary><i>Previously, mancap (Manca Pezzot) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

hello

**Review by gbaasch — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mancap/branching/5#-:-LQfX6BC2zLVkEkip99f:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @mancap)

**Pull request closed without merging**
